[manager]
show_hidden = true

[opener]

edit = [
  { run = 'nvim "$@"', block = true, for = "unix" }
]

play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" }
]

open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
